### ISSUE TITLE
drag and drop of image from one scrollview to another scrollview

### ISSUE THREAD

**Issue by radhar** [calimarkus/JDDroppableView#1]
Hi
Please any one help me out.

The project reqiurements are:

1)The app supports   only for ipad and landscape mode.

2)It will contain a view with 2 scrollviews one at the top and should scroll vertically only and the other scrollview should scroll horizontally and should be present  at the bottom of the first. The top scrollview should show or fit 8 images at a time(2 rows with 4 columns) and rest images are hidden in contentsize(wen top scrollview is scrolled the rest images  will be seen). The bottom scrollview height should same as the height of the image or imageview. The top scrollview height should be greater than the 2*height of image or imageview. The width of the  top scrollview and bottom scrollview should be same as the width of the frame.

3)The duplicate copy of image or imageview should be dragged from top scrollview to bottom scroll view.

4)If the previously or already placed image in bottom scrollview is moved out of the bottom scrollview than the image should be deleted.

I have developed a demo app by copying your logical but unable to do the following:

1)the original image is dragged instead of duplicate or copy  of image.
2)unable to do the 4 point of requirement.

I wanted your help in my project as i am trying since many days but unable to complete this task.

If you like or advice me to send the demo app developed by me for your better idea of the requirement then i will send.

please please  help me.......

waiting for your response

**Comment by mrhaxic** [comment]
@calimarkus there is an example for that? Appreciate
